name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'bump type, major or minor or patch or empty string'
        default: ''
      dry_run:
        description: 'dry run, true or false'
        default: 'false'
      draft:
        description: 'draft, true or false'
        default: 'false'
      pre_release:
        description: 'pre release, true or false'
        default: 'false'
  # schedule:
  # UTC: every 1st and 15th day of month at 9:00
  # JST: every 1st and 15th day of month at 0:00
  # - cron: '0 9 1,15 * *'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Create release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b release
          git push origin release
      # default npm version is 8.3.1, but its version is failed npm install
      # required 8.5.0
      - run: npm i -g npm@8
      - run: npm -v
      - run: npm install
      - run: npm run build
      - run: npm run test
      - uses: MeilCli/bump-release-action@master
        with:
          config_path: '.github/bump.yml'
          bump: ${{ github.event.inputs.bump }}
          dry_run: ${{ github.event.inputs.dry_run }}
          draft: ${{ github.event.inputs.draft }}
          pre_release: ${{ github.event.inputs.pre_release }}
  publish-release:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'release'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      # default npm version is 8.3.1, but its version is failed npm install
      # required 8.5.0
      - run: npm i -g npm@8
      - run: npm -v
      - run: npm install
      - name: Push package-lock.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-action"
          git add package-lock.json
          git commit -m "update package-lock.json" -a
          git push origin release
      - run: npm run build
      - run: npm run copy
      - run: npm publish --access public --workspaces
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Pull Request
        uses: octokit/request-action@v2.x
        id: create_pull_request
        env:
          GITHUB_TOKEN: ${{ secrets.MEILCLI_BOT }}
        with:
          route: POST /repos/{owner}/{repo}/pulls
          owner: MeilCli
          repo: notion-db-notification
          title: 'version up'
          head: 'release'
          base: 'master'
      - name: Add Assign
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.MEILCLI_BOT }}
        with:
          route: POST /repos/{owner}/{repo}/issues/{issue_number}/assignees
          owner: MeilCli
          repo: notion-db-notification
          issue_number: ${{ fromJson(steps.create_pull_request.outputs.data).number }}
          assignees: '["MeilCli"]'
      - name: Add Reviewer
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.MEILCLI_BOT }}
        with:
          route: POST /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers
          owner: MeilCli
          repo: notion-db-notification
          pull_number: ${{ fromJson(steps.create_pull_request.outputs.data).number }}
          reviewers: '["MeilCli"]'
